### ISSUE TITLE
 unable to communicate with CoolQ Client

### ISSUE THREAD

**Issue by benbenshadow** [Earth-Online/efb-qq-coolq-docker#1]
安装readme 修改配置文件， 启动后tg收到这个消息， 无法连接coolq client

We're unable to communicate with CoolQ Client.
Please check the connection and credentials provided.
Unable to connect to CoolQ Client!Error Message:
HTTPConnectionPool(host='cqhttp', port=5700): Max retries exceeded with url: /get_status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd8b545908>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by blue-bird1** [comment]
这是因为双方同时启动,而coolq还没有登陆成功,所以连接失败了, 登陆后用机器人 /extra 里的命令重连一下

**Comment by benbenshadow** [comment]
收到回复，受宠若惊。非常感谢作者回复，现在已经正常运行了

**Comment by kevinzhang1234** [comment]
> 收到回复，受宠若惊。非常感谢作者回复，现在已经正常运行了

请问你是怎么解决的，我的还是不行
